# Generated by Django 4.2.13 on 2024-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_attempt', models.DateTimeField(auto_now_add=True, verbose_name='время попытки')),
                ('status', models.CharField(choices=[('successful', 'успешно'), ('unsuccessful', 'не успешно')], max_length=100, verbose_name='статус попытки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='электронная почта клиента')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя клиента')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Страна')),
                ('identity_nalog_number', models.IntegerField(verbose_name='ИНН')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sending', models.DateTimeField(verbose_name='дата и время отправки')),
                ('time_end', models.DateTimeField(verbose_name='дата и время окончания')),
                ('periodicity', models.CharField(choices=[('once a week', 'один раз в неделю'), ('everyday', 'каждый день'), ('once a month', 'один раз в месяц')], max_length=100, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], max_length=100, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('can_view_mailing', 'Может просматривать рассылки'), ('can_disable_mailing', 'Может отключать рассылки'), ('cannot_edit_mailing', 'Не может редактировать рассылки'), ('cannot_manage_mailing', 'Не может управлять списком рассылок'), ('cannot_change_mailing', 'Не может создавать рассылки')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='тема сообщения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст сообщения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='картинка сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'permissions': [('cannot_change_message', 'Не может изменять сообщения')],
            },
        ),
    ]
